# Generated by Django 4.1.7 on 2023-04-02 21:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('date_observed', models.DateField(default=django.utils.timezone.now)),
                ('time_observed', models.TimeField(default=datetime.time(21, 19, 53, 578631))),
                ('location_observed', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('number_observed', models.IntegerField(default=1)),
                ('field_notes', models.TextField(max_length=250)),
            ],
        ),
    ]
