# Generated by Django 4.1.7 on 2023-04-02 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='time_observed',
            field=models.TimeField(default=datetime.time(21, 25, 50, 554919)),
        ),
    ]
