# Generated by Django 4.1.7 on 2023-04-02 21:34

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bird_time_observed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='time_observed',
            field=models.TimeField(default=main_app.models.get_current_time),
        ),
    ]
